### ISSUE TITLE
juliaberry.github.io feedback

### ISSUE THREAD

**Issue by kimttfung** [JuliaBerry/JuliaBerry.jl#3]
Hi! I thought I just wanted to give some feedback for the [juliaberry.github.io site](https://juliaberry.github.io/) because I thought the instructions were slightly confusing.
As you can see, there are 2 sections named "Installing Julia" and "Compiling Julia". From a beginner's perspective, coming in I didn't know what "compiling" meant and I thought that both "installing Julia" and "compiling Julia" were necessary. I ended up doing both and when I was compiling, it installed almost 32GiB worth of files and that exceeded the storage of my SD card. So I think we should add something telling the reader that only one of "Installing Julia" and "Compiling Julia" is necessary and not both. Also, we can add a message saying that "IJulia notebook" is optional and only for users that want to install Jupyter Notebook. In addition, I spoke to Avik earlier and he said that `apt` gets you 1.0 whereas on the website it says that `apt` only gets you 0.6. Maybe we should get that updated too, and add the actual command we need for installing via `apt`.
w/ @logankilpatrick

Thanks & have a nice day! :-)

**Comment by logankilpatrick** [comment]
I'm currently swamped and out of town till January 20th. When I'm back in Boston, I plan to set up my Raspberry pie and can update the docs and such for this with you @fungktt

**Comment by kimttfung** [comment]
Got a pull request out so that the website can have a temporary update: https://github.com/JuliaBerry/juliaberry.github.io/pull/3

**Comment by aviks** [comment]
Fixed by #3 . thanks again @fungktt

**Comment by kimttfung** [comment]
No problem! @aviks
